# Generated by Django 5.1.3 on 2024-11-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsitcloud', '0002_theme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default_name', max_length=100, unique=True)),
                ('theme', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
