# Generated by Django 5.1.3 on 2024-12-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default_theme', max_length=100, unique=True)),
                ('theme', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
