# Generated by Django 5.1.3 on 2024-12-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myadmin',
            old_name='title',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='myadmin',
            old_name='theme',
            new_name='value',
        ),
    ]
