# Generated by Django 5.1.3 on 2024-12-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='techmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='techmark', max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
